//
// Created by BZLZHH on 2025/2/8.
//

#ifndef MOBILEGLUES_VERSION_H

#define VERSION_DEVELOPMENT 0
#define VERSION_ALPHA 1
#define VERSION_BETA 2
#define VERSION_RC 3
#define VERSION_RELEASE 10

#define MAJOR 1
#define MINOR 3
#define REVISION 2
#define PATCH 0

#define VERSION_TYPE VERSION_DEVELOPMENT

#if VERSION_TYPE == VERSION_RC
#define VERSION_RC_NUMBER 1
#endif

#define VERSION_SUFFIX ""

#define MOBILEGLUES_VERSION_H

#endif // MOBILEGLUES_VERSION_H
